### ISSUE TITLE
The correct command should be `tar -xf dockerbox-img.tar.gz -C /usr/local/share/dockerbox`

### ISSUE THREAD

**Issue by LeeLin2602** [leafoliage/freebsd-dockerbox#4]
I am not sure if it is a problem, but at least, on my freebsd14, the correct command is like above.
For your information.

**Comment by leafoliage** [comment]
Thanks for the heads up. Resolved with [3eb8d9c](https://github.com/leafoliage/freebsd-dockerbox/commit/3eb8d9c551ab858518fd3acdb3490bd64ec0f64f)
